export type GameErrorCode =
  | 'INVALID_TOKEN_SELECTION'
  | 'TOKENS_MUST_BE_DIFFERENT'
  | 'TOKEN_NOT_AVAILABLE'
  | 'TOKEN_LIMIT_EXCEEDED'
  | 'NOT_ENOUGH_TOKENS'
  | 'CANNOT_BUY_CARD'
  | 'CARD_NOT_FOUND'
  | 'RESERVE_LIMIT_REACHED'
  | 'INVALID_PAYMENT'
  | 'DECK_EMPTY'
  | 'UNKNOWN_ACTION_TYPE';
